sudo: required

language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: utplsql
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master

env:
  global:
    #Oracle 11g XE R2 variables
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - ORA_SDTZ='Europe/London' #Needed as a client parameter
    - TZ='Europe/London'       #Needed as a DB Server parameter
    #Adding SQLPlus to path
    - PATH=$PATH:$ORACLE_HOME/bin
    # project variables
    - DB_USER=ut3_demo
    - DB_PASS=LHZYPbWvYdu2ctp8
    ##utPLSQL variables
    - UTPLSQL_DIR="utPLSQL"
    - UTPLSQL_V2_DIR="utPLSQL_V2"
before_install:
  # download travis-oracle
  - wget 'https://github.com/cbandy/travis-oracle/archive/v2.0.2.tar.gz'
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.2.tar.gz
  # download latest utPLSQL release
  - curl -LOk $(curl --silent https://api.github.com/repos/utPLSQL/utPLSQL/releases/latest | awk '/browser_download_url/ { print $2 }' | grep ".zip" | sed 's/"//g')
  - unzip -q utPLSQL.zip
  # download utPLSQL v.2.3.1 release
  - curl -LOk $(curl --silent https://api.github.com/repos/utPLSQL/utPLSQL/releases/3608515 | awk '/browser_download_url/ { print $2 }' | grep ".zip" | sed 's/"//g')
  - unzip -d ${UTPLSQL_V2_DIR} -q utplsql-2-3-1.zip
  # download utPLSQL-cli
  - curl -Lk -o utPLSQL-cli.zip https://bintray.com/viniciusam/utPLSQL-cli/download_file?file_path=utPLSQL-cli-develop-201706191645.zip
  - unzip -q utPLSQL-cli.zip
  # download Oracle XE installer for Travis
  - .travis/oracle/download.sh

install:
  # Install Oracle Database
  - .travis/oracle/install.sh
  # Install utPLSQL v3
  - .travis/install_utplsql.sh
  # Install utPLSQL v2.3.1
  - .travis/install_utplsql_v2.3.1.sh
  # Create user
  - .travis/setup_account.sh
  # Install project sources and tests
  - source/install.sh
  - source/uninstall.sh
  - source/install.sh
  - test/install.sh

script:
  # Run tests
  - utPLSQL-cli/bin/utplsql run ${DB_USER}/${DB_PASS}@127.0.0.1:1521/xe -source_path=source -test_path=test -f=ut_documentation_reporter -c -f=ut_coverage_sonar_reporter -o=coverage.xml -f=ut_sonar_test_reporter -o=test_results.xml
  # Run sonar scanner and publish to sonar
  - sonar-scanner
